services:
  llama-cpp-turboquant:
    build: .
    image: llama-cpp-turboquant
    container_name: llama-cpp-turboquant
    restart: no
    # unless-stopped
    # command: /build/build/bin/llama-bench
    #   -hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:MXFP4_MOE
    #   -ngl 99
    #   -t 6
    #   -p 4096
    #   -n 64
    #   -b 1024
    #   -ub 1024
    #   --n-cpu-moe 17
    #   -ctk turbo4
    #   -ctv turbo2
    command: llama-server
      -hf ISTA-DASLab/Qwen3.8-27B-GSQ-RCO-GGUF:IQ3_S
      --alias qwen3.8-27b-gsq-rco
      --ctx-size 65536
      --batch-size 512
      --ubatch-size 512
      --n-gpu-layers 99
      --no-mmap
      --parallel 1
      --models-max 1
      --mlock
      --threads 6
      --temp 0.7
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --reasoning on
      --chat-template-kwargs '{"reasoning_effort":"medium"}'
      --ctx-checkpoints 128
      --cache-ram 6000
      -ctk turbo4
      -ctv turbo2
      --jinja
      --cache-reuse 256
      --host 0.0.0.0
      --port 8080
    environment:
      LLAMA_CACHE: /models
      HF_TOKEN: ""
    ports:
      - "8123:8080"
    volumes:
      - /opt/generated/models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]