services:
  filebrowser:
    image: gtstef/filebrowser:stable
    container_name: filebrowser-quantum
    restart: unless-stopped
    volumes:
      - /mysatapool/cache:/cache
      - /mysatapool/zdata:/srv/zpool
      - /mnt/media:/srv/media
      - /mnt/extra:/srv/extra
      - ./data:/home/filebrowser/data
    ports:
      - "${PORT:-8448}:80"
