#!/bin/bash

# Default values
MODEL_SIZE="s"
IMG_SIZE="320"

# Help function
usage() {
    echo "Usage: $(basename "$0") [OPTIONS]"
    echo "Builds a YOLOv9 ONNX model using Docker."
    echo ""
    echo "Options:"
    echo "  -m, --model-size SIZE   Set model size (default: s; options: t, s, m, c, e)"
    echo "  -i, --img-size SIZE     Set image size (default: 320, options: 320 or 640)"
    echo "  -h, --help              Display this help message"
    exit 0
}

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -m|--model-size) MODEL_SIZE="$2"; shift ;;
        -i|--img-size) IMG_SIZE="$2"; shift ;;
        -h|--help) usage ;;
        *) echo "Unknown parameter passed: $1"; usage ;;
    esac
    shift
done

# Validate arguments
if ! [[ "$IMG_SIZE" =~ ^[0-9]+$ ]]; then
    echo "Error: IMG_SIZE must be an integer."
    exit 1
fi

if [[ ! "$MODEL_SIZE" =~ ^(t|s|m|c|e)$ ]]; then
    echo "Error: MODEL_SIZE must be one of: t, s, m, c, e."
    exit 1
fi

echo "Building model with SIZE=${MODEL_SIZE} and IMG_SIZE=${IMG_SIZE}..."

if docker build . --build-arg MODEL_SIZE="${MODEL_SIZE}" --build-arg IMG_SIZE="${IMG_SIZE}" --output ./config/model_cache/ -f- <<'EOF'; then
FROM python:3.11 AS build
RUN apt-get update && apt-get install --no-install-recommends -y libgl1 && rm -rf /var/lib/apt/lists/*
COPY --from=ghcr.io/astral-sh/uv:0.8.0 /uv /bin/
WORKDIR /yolov9
ADD https://github.com/WongKinYiu/yolov9.git .
RUN uv pip install --system -r requirements.txt
RUN uv pip install --system onnx==1.18.0 onnxruntime onnx-simplifier>=0.4.1 onnxscript
ARG MODEL_SIZE
ARG IMG_SIZE
ADD https://github.com/WongKinYiu/yolov9/releases/download/v0.1/yolov9-${MODEL_SIZE}-converted.pt yolov9-${MODEL_SIZE}.pt
RUN sed -i "s/ckpt = torch.load(attempt_download(w), map_location='cpu')/ckpt = torch.load(attempt_download(w), map_location='cpu', weights_only=False)/g" models/experimental.py
RUN python3 export.py --weights ./yolov9-${MODEL_SIZE}.pt --imgsz ${IMG_SIZE} --simplify --include onnx
FROM scratch
ARG MODEL_SIZE
ARG IMG_SIZE
COPY --from=build /yolov9/yolov9-${MODEL_SIZE}.onnx /yolov9-${MODEL_SIZE}-${IMG_SIZE}.onnx
EOF
    echo "Model yolov9-${MODEL_SIZE}-${IMG_SIZE}.onnx built successfully."
else
    echo "Error: Failed to build model."
    exit 1
fi

echo "Pruning Docker system..."
docker system prune -a
